[package]
name = "topiary-playground"
description = "The WebAssembly code that runs at https://topiary.tweag.io/playground"
categories = ["development-tools", "text-processing", "webassembly"]
keywords = [
  "code-formatter",
  "formatter",
  "text",
  "tree-sitter",
  "wasm",
  "webassembly",
]
version = "0.0.1"
edition = "2021"
authors = ["Tweag"]
homepage = "https://topiary.tweag.io/playground"
repository = "https://github.com/topiary/playground"
documentation = "https://topiary.tweag.io/book"
readme = "README.md"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
topiary-core = "0.5.1"
topiary-config = "0.5.1"
topiary-tree-sitter-facade = "0.5.1"
wasm-bindgen = "=0.2.91"
wasm-bindgen-futures = "=0.4"

[build-dependencies]
itertools = "0.11"
topiary-core = "0.5.1"
