name: Release

permissions:
  contents: write

on:
  # FOR DEBUGGING
  pull_request:

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  # Build Playground WASM assets
  build-playground-wasm:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up build tooling
        uses: ./.github/actions/nix-build
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          auth_token: "${{ secrets.CACHIX_TWEAG_TOPIARY_AUTH_TOKEN }}"

      - name: Build WASM assets
        run: nix build

      - name: Upload build artefacts
        uses: actions/upload-artifact@v6
        with:
          name: playground-wasm
          path: result/**


  # Get the appropriate Topiary and Tree-sitter versions
  get-versions:

    runs-on: ubuntu-latest

    outputs:
      topiary: ${{ steps.version.outputs.topiary-core }}
      tree-sitter: ${{ steps.version.outputs.tree-sitter }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get versions
        id: version
        run: |
          cargo metadata --format-version 1 --locked \
          | jq -r '
            .packages[]
            | select(.name == "topiary-core" or .name == "tree-sitter")
            | "\(.name)=\(.version)"
          ' \
          | tee -a $GITHUB_OUTPUT


  # Build supported languages grammar WASM, query and example assets
  build-language-assets:
    # TODO

    runs-on: ubuntu-latest
    needs:
      - get-versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          path: playground

      - name: Checkout Topiary
        uses: actions/checkout@v6
        with:
          repository: topiary/topiary
          ref: "v${{ needs.get-versions.outputs.topiary }}"
          path: topiary

      - name: Set up build tooling
        uses: ./playground/.github/actions/nix-build
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          auth_token: "${{ secrets.CACHIX_TWEAG_TOPIARY_AUTH_TOKEN }}"

      - name: Build supported language grammar assets
        run: |
          mkdir build
          cd build

          nix run ../playground#build-wasm-grammars -- ../topiary/languages.ncl
          nix run ../playground#build-languages-export -- ../topiary

      - name: Upload build artefacts
        uses: actions/upload-artifact@v6
        with:
          name: language-assets
          path: build/*


#  # Bundle the above assets with the htdocs and cut a GitHub release
#  create-release:
#    # TODO
#
#    runs-on: ubuntu-latest
#    needs:
#      - build-playground-wasm
#      - build-language-assets
#
#    # NOTE Need to download Tree Sitter 0.22.6 (the version used in
#    # Topiary 0.5.1) WASM assets:
#    # - https://github.com/tree-sitter/tree-sitter/releases/download/v0.22.6/tree-sitter.js
#    # - https://github.com/tree-sitter/tree-sitter/releases/download/v0.22.6/tree-sitter.wasm
#    #
#    # These should be bundled with the grammar assets in
#    # web-playground/public/scripts
#
#
#  # Once the release is available, trigger the website to build
#  trigger-website-build:
#    # TODO
#
#    runs-on: ubuntu-latest
#    needs:
#      - create-release
